// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeBGSxkiDpGygOYB8-H3upfPx6s8cGza8',
    appId: '1:71997905902:web:6ac1c39ac0b8a901b2ccff',
    messagingSenderId: '71997905902',
    projectId: 'roomy-ai-app',
    authDomain: 'roomy-ai-app.firebaseapp.com',
    storageBucket: 'roomy-ai-app.firebasestorage.app',
    measurementId: 'G-3RZNVCK771',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP_k2Gl7vvcOLkfGf_E_p0hEuQ72dubLw',
    appId: '1:71997905902:android:86b1e9453bf9bd06b2ccff',
    messagingSenderId: '71997905902',
    projectId: 'roomy-ai-app',
    storageBucket: 'roomy-ai-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOARNpoJGG0Uphv6WcdUyJxAGUaZH9AJ8',
    appId: '1:71997905902:ios:e2176ca2451aa103b2ccff',
    messagingSenderId: '71997905902',
    projectId: 'roomy-ai-app',
    storageBucket: 'roomy-ai-app.firebasestorage.app',
    iosBundleId: 'com.example.roomai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOARNpoJGG0Uphv6WcdUyJxAGUaZH9AJ8',
    appId: '1:71997905902:ios:e2176ca2451aa103b2ccff',
    messagingSenderId: '71997905902',
    projectId: 'roomy-ai-app',
    storageBucket: 'roomy-ai-app.firebasestorage.app',
    iosBundleId: 'com.example.roomai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeBGSxkiDpGygOYB8-H3upfPx6s8cGza8',
    appId: '1:71997905902:web:12e491b0dbddcba7b2ccff',
    messagingSenderId: '71997905902',
    projectId: 'roomy-ai-app',
    authDomain: 'roomy-ai-app.firebaseapp.com',
    storageBucket: 'roomy-ai-app.firebasestorage.app',
    measurementId: 'G-LWSSWPT5PG',
  );
}
